version: "3.2"

services:
  db: #TODO deal with postgres user and password differently
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
